# Generated by Django 5.2.7 on 2025-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientactivities',
            name='base_duration',
            field=models.IntegerField(default=0),
        ),
    ]
