from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

pdfmetrics.registerFont(
    TTFont("Zalando", "reports/fonts/ZalandoSans-Light.ttf")
)
pdfmetrics.registerFont(
    TTFont("Zalando-Bold", "reports/fonts/ZalandoSans-SemiBold.ttf")
)

def draw_billing_report(c: canvas.Canvas, report: dict) -> None:
    width, height = A4
    left = 2 * cm
    right = width - 2 * cm
    top = height - 2 * cm
    bottom = 2 * cm

    # ---- typography (Word-like) ----
    BASE_FONT = 12
    LINE = BASE_FONT * 1.35  # ~ Word 1.15 feel
    GAP_SM = 0.4 * cm
    GAP_MD = 0.7 * cm
    GAP_LG = 1.0 * cm

    y = top

    # ---------- helpers ----------
    def new_page():
        nonlocal y
        c.showPage()
        y = top
        _draw_header()

    def ensure_space(needed: float):
        nonlocal y
        if y - needed < bottom:
            new_page()

    def hr(thickness=1):
        nonlocal y
        c.setLineWidth(thickness)
        c.line(left, y, right, y)

    def money(v) -> str:
        try:
            return f"{float(v):.2f} zł"
        except Exception:
            return f"{v} zł"

    def _draw_header():
        nonlocal y
        # Header row
        c.setFont("Zalando-Bold", 16)
        c.drawString(left, y, report.get("client_name", "Client"))

        c.setFont("Zalando", BASE_FONT)
        c.drawRightString(right, y, report.get("month_label", "Month YYYY"))
        y -= LINE

        # Divider
        hr(thickness=1.2)
        y -= GAP_MD

    # ---------- start ----------
    _draw_header()

    activities = report.get("activities", [])

    for idx, a in enumerate(activities, start=1):
        # minimal space for section start
        ensure_space(3 * LINE + GAP_MD)

        # Activity title
        c.setFont("Zalando-Bold", 14)
        c.drawString(left, y, f"{idx}. {a.get('activity_name', 'Activity')}")
        y -= LINE

        # Table header
        c.setFont("Zalando-Bold", BASE_FONT)
        c.drawString(left, y, "Date")
        c.drawString(left + 6.0 * cm, y, "Count / duration")
        y -= (LINE * 0.85)

        c.setLineWidth(0.8)
        c.line(left, y, right, y)
        y -= GAP_SM

        # Rows
        date_lines = a.get("date_lines", [])
        if not date_lines:
            ensure_space(LINE + GAP_SM)
            c.setFont("Zalando-Oblique", BASE_FONT)
            c.drawString(left, y, "No completed lessons in this period.")
            c.setFont("Zalando", BASE_FONT)
            y -= LINE
        else:
            c.setFont("Zalando", BASE_FONT)
            for line in date_lines:
                ensure_space(LINE + GAP_SM)
                c.drawString(left, y, str(line.get("date", "")))
                c.drawString(left + 6.0 * cm, y, str(line.get("text", "")))
                y -= LINE

        # Summary line inside activity
        ensure_space(2 * LINE + GAP_MD)

        y -= GAP_SM
        c.setLineWidth(0.8)
        c.line(left, y, right, y)
        y -= GAP_SM

        lessons_count = a.get("lessons_count", 0)
        total_cost = a.get("total_cost", 0)

        c.setFont("Zalando-Bold", BASE_FONT)
        c.drawString(left, y, f"Summary: {lessons_count} lesson(s)")
        c.drawRightString(right, y, f"Total: {money(total_cost)}")
        y -= LINE

        # Space between activities
        y -= GAP_MD

    # Grand total
    ensure_space(3 * LINE + GAP_LG)

    hr(thickness=1.5)
    y -= GAP_MD

    c.setFont("Zalando-Bold", 15)
    c.drawString(left, y, "Total")
    c.drawRightString(right, y, money(report.get("grand_total", 0)))
    y -= (LINE + GAP_LG)

    # Footer
    c.setFont("Zalando", 9)
    c.drawString(left, bottom - 0.6 * cm, "Generated by TutorApp")