# Generated by Django 5.2.7 on 2025-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default='2025-11-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
