# Generated by Django 5.2.7 on 2025-11-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientactivities_base_duration'),
        ('schedule', '0002_schedule_charge_schedule_date_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='clients.clientactivities'),
        ),
    ]
