# Generated by Django 5.2.7 on 2025-11-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
