# Generated by Django 5.2.7 on 2025-11-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
